API
carlos-ssh/librero pull request #3
Opened 2021-12-14 04:49 UTC by carlos-ssh

- Fix issues removinf items.
- Add key for api.

2021-12-14 04:57 UTC, omar-labana commented
Hi @carlos-ssh, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, where the linters checks are not passing.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2021-12-14 05:35 UTC, omar-labana requested changes
Hi @carlos-ssh, 

Excellent work so far! 👌
You have implemented almost all the required features. ✔️ 
There are some cases that you need to adjust but you are almost done! 😀

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-14 05:35 UTC, omar-labana commented on src/components/AddBook.js
> +        </a>
- [ ] Adding a book through a runtime error. Also, `actions` are not correctly dispatched to the store. Please fix these issues. 
![image](https://user-images.githubusercontent.com/33767951/145938721-5e046505-2d2b-4924-8483-03be1b3cc87c.png)

2021-12-14 05:35 UTC, omar-labana commented on src/redux/books/books.js
> +};
- [ ] The initial request to the Bookstore API fails each time the component renders with these log errors. Kindly, update the store config (There are no logged actions and the logger library found in your package,json) then make sure actions are dispatched correctly. I'd suggest using react dev tools for a better insight on what is rendered.
![image](https://user-images.githubusercontent.com/33767951/145938909-0f6f18d5-8945-49b8-9d7a-46b04fb16ae1.png)

2021-12-14 05:40 UTC, carlos-ssh commented on src/components/AddBook.js
> +        </a>
I have the project working well on my desktop:
![Screen Shot 2021-12-13 at 23 39 34](https://user-images.githubusercontent.com/22258274/145939652-cb5e6b13-706e-4317-aa43-571af36e9c79.png)

2021-12-14 11:39 UTC, omar-labana commented on src/components/AddBook.js
> +        </a>
Hey @carlos-ssh, I double-checked your project and the issue still persists, do you mind re-cloning the repo?

2021-12-14 14:48 UTC, carlos-ssh commented on src/components/AddBook.js
> +        </a>
Thanks for answer @omar-labana. I tried to download it last night, but i had the same issues than you!. Thanks a lot for your support and i will keep working on it to fix it ASAP. 
# 💯😄🧑‍🏭

2021-12-15 18:16 UTC, Lameck1 approved these changes
Hi, @carlos-ssh,

You've done well working on the previous review concerns 👏🏼
The tasks for this milestone are therefore successfully implemented 💯.
All the best with the next milestone.

You are free to merge this branch :shipit:.

Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-15 18:21 UTC, merged